# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mj9UkRH0nsfIhNSXxDCe1xKiBZGY5-e6
"""

import pandas as pd
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

uploaded

import pandas as pd
import numpy as np

data = pd.read_csv('duplicate_free_41K.csv')
truncat = data[:30000]
truncat.values[0][4]





!pip install bs4
!pip install selenium
!apt-get update # to update ubuntu to correctly run apt install
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin
import sys
sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')
from selenium import webdriver
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
driver = webdriver.Chrome('chromedriver',chrome_options=chrome_options)

from selenium.webdriver.common.keys import Keys
import time
from bs4 import BeautifulSoup

#Iterate over this next part 

import sys
import csv
sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')
from selenium import webdriver
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
driver = webdriver.Chrome('chromedriver',chrome_options=chrome_options)
driver = webdriver.Chrome('chromedriver',chrome_options=chrome_options)
with open('mycsv3.csv','w',newline='') as f: #name the file "mycsv3_[start]_[end].csv"
    fieldnames = ['id', 'poster', 'title', 'year', 'rating', 'genre', 'action', 'adventure', 'animation', 'comedy', 'crime', 'drama', 'fantasy', 'horror',
                  'mystery', 'romance', 'sci-fi', 'short', 'thriller', 'plot']
    thewriter = csv.DictWriter(f,fieldnames=fieldnames)
    thewriter.writeheader()
    start; #first movie 
    end; #last movie
    for i in range(start,end): 
        driver.get('https://www.google.com')
        inputElms = driver.find_elements_by_css_selector('input[name=q]')
        for inputElm in inputElms:
          #inputElm.send_keys(titles[i] + 'imdb')
          inputElm.send_keys(truncat.values[i][2] +"("+truncat.values[i][3]+") - IMDb")
          inputElm.send_keys(Keys.ENTER)
          time.sleep(1)
          page_source = driver.page_source
          soup = BeautifulSoup(page_source, 'lxml')
          try:
            driver.find_element_by_class_name('yuRUbf').find_element_by_tag_name('a').click()
            time.sleep(2)
            page_source = driver.page_source
            soup = BeautifulSoup(page_source, 'lxml')
            present=0
            try:
              diver = soup.find('div', class_='inline canwrap').find('span').get_text() 
              present=1
            except:
              print("I") 
            #print(diver)
            if i%100==0:
              print(i)
            if(present==1):
              thewriter.writerow({'id' : truncat.values[i][0], 'poster' : truncat.values[i][1], 'title' : truncat.values[i][2], 'year' : truncat.values[i][3],
              'rating' : truncat.values[i][4], 'genre' : truncat.values[i][5], 'action' : truncat.values[i][6],
              'adventure' : truncat.values[i][7], 'animation' : truncat.values[i][8], 'comedy' : truncat.values[i][9],
              'crime' : truncat.values[i][10], 'drama' : truncat.values[i][11], 'fantasy' : truncat.values[i][12],  'horror' : truncat.values[i][13],
              'mystery' : truncat.values[i][14], 'romance' : truncat.values[i][15], 'sci-fi' : truncat.values[i][16], 'short' : truncat.values[i][17], 
              'thriller' : truncat.values[i][18], 'plot' : diver})
          except:
            print ("G")

driver.close()
from google.colab import files
files.download("mycsv3.csv") #same name as the one on line 62
