# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14n7soQxl5LoBg0BURF-VDwY8BMw3imSE
"""

# -*- coding: utf-8 -*-
"""web_scraper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FtZ7Ec725Ue1InIA8kEAPvn5wvRPxJzu
"""

import pandas as pd
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

uploaded

import pandas as pd
import numpy as np

data = pd.read_csv('duplicate_free_41K.csv')
truncat = data[:30000]
truncat.values[0][4]

!pip install bs4
!pip install selenium
!apt-get update # to update ubuntu to correctly run apt install
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin
import sys
sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')
from selenium import webdriver
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')

from selenium.webdriver.common.keys import Keys
import time
from bs4 import BeautifulSoup


import csv
driver1 = webdriver.Chrome('chromedriver',chrome_options=chrome_options)
driver2 = webdriver.Chrome('chromedriver',chrome_options=chrome_options)
with open('mycsv_8000_12000.csv','w',newline='') as f:
    fieldnames = ['id', 'poster', 'title', 'year', 'rating', 'genre', 'action', 'adventure', 'animation', 'comedy', 'crime', 'drama', 'fantasy', 'horror',
                  'mystery', 'romance', 'sci-fi', 'short', 'thriller', 'plot']
    thewriter = csv.DictWriter(f,fieldnames=fieldnames)
    thewriter.writeheader()
    start=8000
    end=12000
    driver1.get('https://www.google.com')
    driver2.get('https://www.google.com')
    time.sleep(2)
    for i in range(start,end): 
        #driver.get('https://www.google.com')
        if(i%2==0):
          driver=driver2
        else:
          driver=driver1
        inputElms = driver.find_elements_by_css_selector('input[name=q]')
        for inputElm in inputElms:
          #inputElm.send_keys(titles[i] + 'imbd')
          s = int(truncat.values[i][3])
          year = str(s)
          url = truncat.values[i][2]+" ("+year+") - IMDb"
          #url = truncat.values[i][2] + " ("+year+")"
          if i%1000==0:
            print(url)
          inputElm.send_keys(url)
          inputElm.send_keys(Keys.ENTER)
          '''
          page_source = driver.page_source
          soup = BeautifulSoup(page_source, 'lxml')
          '''
          try:
            driver.find_element_by_class_name('yuRUbf').find_element_by_tag_name('a').click()
            time.sleep(1)
            page_source = driver.page_source
            soup = BeautifulSoup(page_source, 'lxml')
            present=1
          except:
            print("google search fail")
            present=0
            driver1 = webdriver.Chrome('chromedriver',chrome_options=chrome_options)
            driver2 = webdriver.Chrome('chromedriver',chrome_options=chrome_options)
            driver1.get('https://www.google.com')
            driver2.get('https://www.google.com')
          if(i%2==0):
            driver2.get('https://www.google.com')
          else:
            driver1.get('https://www.google.com')
          if(present==1):
            try:
              diver = soup.find('div', class_='inline canwrap').find('span').get_text() 
              thewriter.writerow({'id' : truncat.values[i][0], 'poster' : truncat.values[i][1], 'title' : truncat.values[i][2], 'year' : truncat.values[i][3],
              'rating' : truncat.values[i][4], 'genre' : truncat.values[i][5], 'action' : truncat.values[i][6],
              'adventure' : truncat.values[i][7], 'animation' : truncat.values[i][8], 'comedy' : truncat.values[i][9],
              'crime' : truncat.values[i][10], 'drama' : truncat.values[i][11], 'fantasy' : truncat.values[i][12],  'horror' : truncat.values[i][13],
              'mystery' : truncat.values[i][14], 'romance' : truncat.values[i][15], 'sci-fi' : truncat.values[i][16], 'short' : truncat.values[i][17], 
              'thriller' : truncat.values[i][18], 'plot' : diver})
            except:
              print("IMDB fail") 
              #driver.get('https://www.imdb.com')
              #time.sleep(2)
               #print(diver)
          if i%100==0:
            print(i)
           
driver.close()
from google.colab import files
files.download("mycsv_8000_12000.cs")

from google.colab import files
files.download("mycsv_8000_12000.csv")